name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:          
          HUGO_VERSION: 0.101.0
          HUGO_EXTENDED: true
          TARGET_REPO: muratcanakcay/muratcanakcay.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.TOKEN }}          
          CNAME: www.muratcanakcay.com
